name: End-to-end tests
on: push
jobs:
  test-build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Set the required Node.js version  
      
      - name: Install dependencies
        run: npm install # Install dependencies for the Electron app
          
      - name: Build Electron app
        run: npm run start # Modify this command to your actual build script if different
    
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6